import {submitRating,aggregateCaseRatings} from '../../../../apps/electron/src/main/lib/review/judging-service.ts';
import {pushViaOutbox} from '../../../../apps/electron/src/main/lib/review/batch-store.ts';
import {existsSync,mkdtempSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
process.env.PROFER_CONFIG_DIR=mkdtempSync(join(tmpdir(),'cdut-review-rating-probe-'));
const rubric:any={dimensions:[{id:'a',name:'质量',min:1,max:5,weight:0.5},{id:'b',name:'可行性',min:1,max:5,weight:0.5}],totalPrecision:2,missingStrategy:'block'};
const input:any={assignmentId:'a1',reviewerId:'j1',caseId:'c1',rubricVersion:1,rubric,scores:[{dimensionId:'a',score:4,na:false},{dimensionId:'b',score:4,na:false}],publicFeedback:''};
const assignments:any=[{id:'a1',caseId:'c1',reviewerId:'j1',rubricVersion:1,recused:false,status:'submitted'},{id:'a2',caseId:'c1',reviewerId:'j2',rubricVersion:1,recused:false,status:'assigned'}];
const duplicated=submitRating(submitRating([],input),input);
const nan=submitRating([],{...input,scores:[{dimensionId:'a',score:NaN,na:false},{dimensionId:'b',score:4,na:false}]});
const na=submitRating([],{...input,scores:[{dimensionId:'a',score:null,na:true},{dimensionId:'b',score:4,na:false}]});
let release:any;let entered:any;
const waiting=new Promise(resolve=>{entered=resolve});
const port:any={kind:'mock',push:()=>{entered();return new Promise(resolve=>{release=resolve})}};
const pending=pushViaOutbox(port,{caseId:'c1',actionId:'durable-action',actionKind:'decision',baseExternalRevision:0,body:{result:'pass'}});
await waiting;
const writtenBeforePushCompletes=existsSync(join(process.env.PROFER_CONFIG_DIR!,'sync-outbox/durable-action.json'));
release({id:'rcp1',actionId:'durable-action',externalSystem:'mock',caseId:'c1',expectedExternalRevision:0,payloadHash:'',status:'accepted'});
await pending;
console.log(JSON.stringify({duplicatedVotes:duplicated.length,missingJudgeBypassedTotal:aggregateCaseRatings(rubric,assignments,duplicated,'c1').total,nanAccepted:Number.isNaN(nan[0].scores[0].score),naTotal:aggregateCaseRatings(rubric,assignments.slice(0,1),na,'c1').total,naExpectedWhenExcluded:4,emptyBlockTotal:aggregateCaseRatings(rubric,[],[],'c1').total,outboxWrittenBeforePushCompletes:writtenBeforePushCompletes},null,2));
