import {createCaseFromTemplate,updateFields,correctObservation,setEvidenceLink} from '../../../../apps/electron/src/main/lib/review/application-service.ts';
import {getTemplate,saveDraft,publishTemplate} from '../../../../apps/electron/src/main/lib/review/template-store.ts';
import {publishComprehensiveFixture} from '../../../../apps/electron/src/main/lib/review/fixtures/comprehensive-fixture.ts';
import {readAggregate} from '../../../../apps/electron/src/main/lib/review/case-store-v2.ts';
import {ensureInitialTask,recordStageDecision,resolveSupplementV2} from '../../../../apps/electron/src/main/lib/review/stage-workflow.ts';
import {exportRoundTripPackage,importRoundTripPackage,resetRoundTripDedup} from '../../../../apps/electron/src/main/lib/review/offline-roundtrip.ts';
import {runReviewCaseV2} from '../../../../apps/electron/src/main/lib/review/run-service-v2.ts';
import {getRunV2,readArtifact} from '../../../../apps/electron/src/main/lib/review/run-store-v2.ts';
import {resourceCheck} from '../../../../apps/electron/src/main/lib/review/resource-check.ts';
import {rmSync,mkdtempSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
const qaRoot=mkdtempSync(join(tmpdir(),'cdut-review-service-probe-'));
process.env.PROFER_CONFIG_DIR=join(qaRoot,'config');
publishComprehensiveFixture({getTemplate,saveDraft,publish:publishTemplate});
const template=getTemplate('comprehensive-assessment-v2',2)!;
const reviewer={actorId:'reviewer',actorSource:'local',role:'reviewer'} as const;
const student={actorId:'student',actorSource:'local',role:'student'} as const;
const payload={title:'隔离复测',fieldValues:{studentName:'测试学生',studentId:'001',academicYear:'2025-2026',applicant:'测试学生'},subjects:[{id:'s1',title:'竞赛',type:'item' as const,fieldValues:{declaredScore:8,category:'competition',level:'national-1',activityDate:'2025-01-01',eventId:'E1'}}]};
const create=async(id:string)=>createCaseFromTemplate(template.templateId,2,payload,reviewer,id);
const cmd=(id:string,type:string,body:any,actor:any=reviewer)=>({requestId:id,type,actor,expectedRevision:readAggregate(body.caseId)?.caseV2.revision??0,payload:body});
const findings:any={};
await create('facts');
await updateFields('facts',{requestId:'update',actor:reviewer,expectedRevision:0,payload:{subjectFieldValues:[{subjectId:'s1',values:{declaredScore:0}}]}});
findings.updatedNumber=readAggregate('facts')!.caseV2.subjects[0].fields.declaredScore;
await correctObservation('facts',{requestId:'correct',actor:reviewer,expectedRevision:1,payload:{subjectId:'s1',fieldKey:'declaredScore',value:{kind:'number',value:7},sourceRefs:[],reason:'人工核对'}});
findings.correctedFact={observation:readAggregate('facts')!.observations.at(-1)?.value,formValue:readAggregate('facts')!.caseV2.subjects[0].fields.declaredScore};
const link=await setEvidenceLink('facts',{requestId:'link',actor:reviewer,expectedRevision:2,payload:{documentVersionId:'nonexistent',subjectIds:['foreign-subject'],supportsFact:'等级',linkedBy:'user'}});
findings.invalidEvidenceAccepted=link.ok;
await create('workflow');
await ensureInitialTask('workflow',template,reviewer);
let a=readAggregate('workflow')!;
const advance=await recordStageDecision('workflow',{requestId:'student-pass',actor:student,expectedRevision:a.caseV2.revision,payload:{action:'stage-pass',taskId:a.tasks[0].id,reason:'学生自行推进系统阶段'}},template);
findings.studentAdvancedSystemTask=advance.ok;
a=readAggregate('workflow')!;
const ret=await recordStageDecision('workflow',{requestId:'return',actor:reviewer,expectedRevision:a.caseV2.revision,payload:{action:'return-for-supplement',taskId:a.tasks.find(t=>t.status==='open')!.id,reason:'缺证',supplementRequiredElements:['证书'],supplementReason:'缺证'}},template);
a=readAggregate('workflow')!;
const resolved=await resolveSupplementV2('workflow',{requestId:'satisfied',actor:reviewer,expectedRevision:a.caseV2.revision,payload:{supplementId:a.supplements[0].id,outcome:'satisfied',reason:'模拟确认'}});
a=readAggregate('workflow')!;
findings.supplementWithoutReply={accepted:resolved.ok,stage:a.caseV2.stage,openTasks:a.tasks.filter(t=>t.status==='open').length,responses:a.supplements[0].responses.length};
const pkg=exportRoundTripPackage(readAggregate('facts')!,'student-reply',{actorId:'student',actorSource:'local'},{studentName:'public'},{studentName:'应更新的姓名'});
const first=importRoundTripPackage(pkg);
resetRoundTripDedup();
findings.offlineReply={receipt:first,storedName:readAggregate('facts')!.caseV2.caseFields.studentName,afterRestartSimulation:importRoundTripPackage(pkg)};
const kinds=['register','parse','ocr','extract','bind','plan','check','calculate','verify','summarize','task'];
let midway:any;
const executors=Object.fromEntries(kinds.map(kind=>[kind,async(node:any,hash:string)=>{if(kind==='parse') midway=getRunV2('facts','checkpoint')?.checkpoints.find(c=>c.nodeId==='node-auto-check-register');return {status:'done',inputHash:hash,artifact:{sourceIds:[],summary:kind}}}])) as any;
await runReviewCaseV2(readAggregate('facts')!.caseV2,template,executors,{runId:'checkpoint'});
findings.midRunCheckpoint=midway;
rmSync(join(process.env.PROFER_CONFIG_DIR!,'review-cases/facts/runs-v2/checkpoint/artifacts/node-auto-check-ocr.json'));
let ocrCalls=0;
await runReviewCaseV2(readAggregate('facts')!.caseV2,template,{...executors,ocr:async(node:any,hash:string)=>{ocrCalls++;return{status:'done',inputHash:hash,artifact:{sourceIds:[],summary:'ocr'}}}},{runId:'resumed',resumeRunId:'checkpoint'});
findings.missingArtifactRecovery={ocrCalls,artifactAvailable:!!readArtifact('facts','resumed','node-auto-check-ocr')};
findings.emptyResourceRoot=resourceCheck(join(qaRoot,'empty-resources'));
console.log(JSON.stringify(findings,null,2));
