import {mkdtempSync,writeFileSync,existsSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createCaseFromTemplate,updateFields,correctObservation,setEvidenceLink,validateFieldValuesV2} from '../../../../apps/electron/src/main/lib/review/application-service.ts';
import {readAggregate} from '../../../../apps/electron/src/main/lib/review/case-store-v2.ts';
import {getTemplate,saveDraft,publishTemplate} from '../../../../apps/electron/src/main/lib/review/template-store.ts';
import {publishComprehensiveFixture} from '../../../../apps/electron/src/main/lib/review/fixtures/comprehensive-fixture.ts';
import {registerMaterial} from '../../../../apps/electron/src/main/lib/review/material-service.ts';
import {submitCaseV2,recordStageDecision,resolveSupplementV2,respondSupplementV2} from '../../../../apps/electron/src/main/lib/review/stage-workflow.ts';
import {exportRoundTripPackage,importRoundTripPackage,buildPublicReport,projectForRole} from '../../../../apps/electron/src/main/lib/review/offline-roundtrip.ts';
import {aggregateRatings,castRating} from '../../../../apps/electron/src/main/lib/review/rating-service.ts';
import {createBatchV2,readBatchStateV2,runBatchQueue,pushViaOutbox} from '../../../../apps/electron/src/main/lib/review/batch-store.ts';
const qa=mkdtempSync(join(tmpdir(),'cdut-g-loop-probe-'));
process.env.PROFER_CONFIG_DIR=join(qa,'config');
const file=join(qa,'certificate.txt');writeFileSync(file,'虚构证明，只作本地复查');
publishComprehensiveFixture({getTemplate,saveDraft,publish:publishTemplate});
const template=getTemplate('comprehensive-assessment-v2',2)!;
const reviewer={actorId:'reviewer',actorSource:'local',role:'reviewer'} as const;
const student={actorId:'student',actorSource:'local',role:'student'} as const;
const revision=(id:string)=>readAggregate(id)!.caseV2.revision;
let seq=0;
const cmd=(id:string,payload:any,actor:any=reviewer)=>({requestId:'probe-'+ ++seq,actor,expectedRevision:revision(id),payload});
async function seed(id:string){
 await createCaseFromTemplate(template.templateId,2,{title:'测试学生',fieldValues:{studentName:'测试学生',studentId:'001',academicYear:'2025-2026',applicant:'测试学生'},subjects:[{id:'s1',title:'测试竞赛',type:'item',fieldValues:{category:'competition',level:'national-1',declaredScore:8,eventId:'E1',activityDate:'2025-01-01'}}]},reviewer,id);
 await registerMaterial(id,cmd(id,{sourcePath:file,role:'evidence'}));
 await submitCaseV2(id);
}
async function openSupplement(id:string){
 await seed(id);
 const a=readAggregate(id)!;
 await recordStageDecision(id,cmd(id,{action:'return-for-supplement',taskId:a.tasks[0].id,reason:'缺少等级证明',supplementRequiredElements:['等级'],supplementReason:'补证'}),template);
 return readAggregate(id)!.supplements[0].id;
}
const out:any={};
await seed('fields');
await updateFields('fields',cmd('fields',{subjectFieldValues:[{subjectId:'s1',values:{declaredScore:0}}]}));
out.ipcStyleNumber=readAggregate('fields')!.caseV2.subjects[0].fields.declaredScore;
const validated=await updateFields('fields',cmd('fields',{subjectFieldValues:[{subjectId:'s1',values:{declaredScore:1}}]}),template);
out.withTemplateScopeResult=validated.ok?'accepted':validated.code;
await correctObservation('fields',cmd('fields',{subjectId:'s1',fieldKey:'declaredScore',value:{kind:'number',value:7},sourceRefs:[],reason:'核对原件'}));
out.correctedFact={observation:readAggregate('fields')!.observations.at(-1)?.value,formValue:readAggregate('fields')!.caseV2.subjects[0].fields.declaredScore};
const link=await setEvidenceLink('fields',cmd('fields',{documentVersionId:'nonexistent-version',subjectIds:['foreign-subject'],supportsFact:'等级',linkedBy:'user'}));
out.invalidEvidenceAccepted=link.ok;
out.invalidDateAccepted=validateFieldValuesV2({...template,fields:[{key:'date',kind:'date',label:'日期',scope:'case',required:true,visibility:'public'}]},'case',{date:'2026-99-99garbage'},new Set(['date'])).length===0;
await seed('role');
const pass=await recordStageDecision('role',cmd('role',{action:'stage-pass',taskId:readAggregate('role')!.tasks[0].id,reason:'学生自行完成自动审核'},student),template);
out.studentAdvancedSystemTask=pass.ok;
const noReply=await openSupplement('no-reply');
await resolveSupplementV2('no-reply',cmd('no-reply',{supplementId:noReply,outcome:'satisfied',reason:'模拟确认'}));
out.satisfiedWithoutReply={responses:readAggregate('no-reply')!.supplements[0].responses.length,openTasks:readAggregate('no-reply')!.tasks.filter(t=>t.status==='open').length};
const insufficient=await openSupplement('insufficient');
await respondSupplementV2('insufficient',cmd('insufficient',{supplementId:insufficient,note:'模糊证明'},student));
await resolveSupplementV2('insufficient',cmd('insufficient',{supplementId:insufficient,outcome:'insufficient',reason:'仍看不清'}));
const again=await respondSupplementV2('insufficient',cmd('insufficient',{supplementId:insufficient,note:'再次补清晰证明'},student));
out.respondAfterInsufficient=again.ok?'accepted':again.code;
const sup=await openSupplement('roundtrip');
const a=readAggregate('roundtrip')!;
const pkg1=exportRoundTripPackage(a,'student-reply',{actorId:'student',actorSource:'local'},{studentName:'public'},{supplementId:sup,note:'第一次提交',documentVersionIds:['d1']});
const first=await importRoundTripPackage(pkg1);
const duplicate=await importRoundTripPackage(pkg1);
const pkg2=exportRoundTripPackage(readAggregate('roundtrip')!,'student-reply',{actorId:'student',actorSource:'local'},{studentName:'public'},{supplementId:sup,note:'第二次提交清晰件',documentVersionIds:['d2']});
const second=await importRoundTripPackage(pkg2);
const sameNotePkg=exportRoundTripPackage(readAggregate('roundtrip')!,'student-reply',{actorId:'student',actorSource:'local'},{studentName:'public'},{supplementId:sup,note:'第一次提交',documentVersionIds:['d2']});
const sameNote=await importRoundTripPackage(sameNotePkg);
const tamperedReplay=await importRoundTripPackage({...pkg1,payload:{...pkg1.payload,projection:{...pkg1.payload.projection,title:'篡改了标题'}}});
out.roundTrip={first:first.status,duplicate:duplicate.status,second,sameNote:sameNote.status,tamperedReplay:tamperedReplay.status,responses:readAggregate('roundtrip')!.supplements[0].responses.map(r=>({note:r.note,documents:r.documentVersionIds}))};
const scores: any={dimensions:[{id:'a',name:'质量',min:1,max:5,weight:1},{id:'b',name:'可行性',min:1,max:5,weight:1}],minEffectiveJudges:2,missingStrategy:'block',totalPrecision:2};
const rating=(actor:string,round:number,values:any)=>({id:actor+'-'+round,caseId:'role',stageId:'rating',actor,scores:values,round,at:''});
out.ratingWithOneJudge=aggregateRatings([rating('j1',1,{a:4,b:4})],scores);
out.ratingMixedRounds=aggregateRatings([rating('j1',1,{a:4,b:4}),rating('j2',2,{a:4,b:4})],scores);
const invalidRating:any=await castRating('role',cmd('role',{stageId:'nonexistent-stage',scores:{ghost:9999}},student));
out.invalidStageRoleScoreAccepted=invalidRating.ok;
const nan:any=await castRating('role',cmd('role',{stageId:'rating',scores:{a:NaN}},{actorId:'judge-9',actorSource:'local',role:'judge'}));
out.nanRejected=nan.ok===false;
const internal='内部处分调查细节';
const projection=projectForRole({...readAggregate('role')!,decisions:[{...readAggregate('role')!.decisions[0],reason:internal}]},'judge',{studentName:'public'},'judge-9');
out.judgeProjection={title:projection.title,hasInternalReason:projection.decisions.some(d=>d.reason.includes(internal)),ownRating:projection.ownRating};
out.publicReportContainsDecisionInternalReason=buildPublicReport({title:'测试学生',fields:{},decisions:[{result:'pass',reason:internal}],supplements:[],internalNotes:['不应公开']},'student').includes(internal);
createBatchV2({id:'missing-executor',name:'执行前置检查',templateId:template.templateId,templateVersion:2,policyVersionLock:[],caseIds:['role'],createdAt:''});
try{await runBatchQueue('missing-executor')}catch(e:any){out.queueError=e.message}
out.queueStatusAfterMissingExecutor=readBatchStateV2('missing-executor')!.status;
let release:any,entered:any;
const started=new Promise(r=>{entered=r});
const pending=pushViaOutbox({kind:'mock',push:async()=>{entered();return new Promise(r=>{release=r})}} as any,{caseId:'role',actionId:'check-pending',actionKind:'decision',baseExternalRevision:0,body:{result:'pass'}});
await started;
out.genericOutboxPersistedBeforeResponse=existsSync(join(process.env.PROFER_CONFIG_DIR!,'sync-outbox/check-pending.json'));
release({id:'receipt',actionId:'check-pending',externalSystem:'mock',caseId:'role',expectedExternalRevision:0,payloadHash:'',status:'accepted'});
await pending;
console.log(JSON.stringify(out,null,2));
